name: Envirenment
on: push

env:
    NODE_ENV: production
    GH_SECRET: ${{ secrets.TEST_SECRET }}

jobs:
    builds:
      runs-on: ubuntu-latest
      steps:
        - name: Print Env Build
          run: |
            echo "${{ env.NODE_ENV }}"
            echo "${{ env.GH_SECRET }}"